- name: Error Handling
  hosts: localhost
  connection: local
  tasks:
    - name: print
      ansible.builtin.shell: cat /etc/passwd | grep DEMO
      ignore_errors: true

    - name: print
      ansible.builtin.shell: ls